import { execSync }
from "child_process";

export function createPullRequest() {

  const branchName =
    `ai-upgrade-${Date.now()}`;

  try {

    console.log(
      "\nCreating Git Branch...\n"
    );

    execSync(
      `git checkout -b ${branchName}`,
      { stdio: "inherit" }
    );

    console.log(
      "\nAdding Files...\n"
    );

    execSync(
      "git add .",
      { stdio: "inherit" }
    );

    console.log(
      "\nCreating Commit...\n"
    );

    execSync(
      `git commit -m "AI dependency upgrades"`,
      { stdio: "inherit" }
    );

    console.log(
      "\nPushing Branch...\n"
    );

    execSync(
      `git push origin ${branchName}`,
      { stdio: "inherit" }
    );

    console.log(
      "\nCreating Pull Request...\n"
    );

    execSync(
      `gh pr create --title "AI Dependency Upgrade" --body "Automated dependency upgrade generated by AI agent."`,
      { stdio: "inherit" }
    );

    console.log(
      "\nPull Request Created\n"
    );

  } catch (err) {

    console.log(
      "\nGit Automation Failed\n"
    );
  }
}